on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:

jobs:
  build:
    runs-on: windows-latest      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Freeze Installer
      run: |
        pyinstaller build.spec 
    - name: Build Installer
      run: |
        iscc installer.iss
    - name: Freeze Portable
      run: |
        pyinstaller --distpath dist-portable build-portable.spec
    - name: Zip Portable 
      shell: pwsh
      run: |
        Copy-Item -Path assets -Destination dist-portable\ -Recurse
        Copy-Item -Path configs -Destination dist-portable\ -Recurse
        Compress-Archive -Path dist-portable -DestinationPath GrimassistPortable.zip
    - name: Upload installer
      uses: actions/upload-artifact@v3
      with:
        name: 'Windows Installer Release'
        path: '\a\grimassist\grimassist\Output\Grimassist Installer.exe'
    - name: Upload portable
      uses: actions/upload-artifact@v3
      with:
        name: 'Windows Portable Release'
        path: '\a\grimassist\grimassist\GrimassistPortable.zip'
